name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Build service
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o target/fnrunner ./cmd/fnrunner/main.go

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}