name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Build runners
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o target/fnrunner ./cmd/fnrunner/main.go
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o target/fnrunner_darwin ./cmd/fnrunner/main.go
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o target/fnrunner.exe ./cmd/fnrunner/main.go


      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}