name: Release

on:
  push:
    tags:
      - "*"
  workflow_run:
    workflows: ["Create tag"]
    types:
      - completed

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: Get the version for tag event
        if: ${{ contains(github.ref, 'refs/tags') }}
        id: get_version_push
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Get the latest tag when a workflow triggered
        id: get_version_manual
        run: echo ::set-output name=VERSION::`git describe --abbrev=0 --tags`

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${{ steps.get_version_push.outputs.VERSION || steps.get_version_manual.outputs.VERSION }}

      - name: Release
        run: |
          docker run \
            --rm \
            --privileged \
            -e CGO_ENABLED=1 \
            --env-file .release-env \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v `pwd`:/go/src/github.com/fnrun/fnrun \
            -v `pwd`/sysroot:/sysroot \
            -w /go/src/github.com/fnrun/fnrun \
            goreleaser/goreleaser-cross:v1.18.0 \
            release --rm-dist --release-notes="changes/${{ steps.get_version.outputs.VERSION }}.md"
