name: Run tests and coverage report
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test: # run only tests with older versions of go
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v -race ./...
  coverage: # run tests and coverage with latest version of go
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v -race -cover -coverprofile=coverage.out ./...
    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.out
        fail_ci_if_error: true